# Generated by Django 4.1.4 on 2022-12-22 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('gradesection', models.CharField(max_length=100)),
                ('cst', models.BooleanField(blank=True)),
                ('icap', models.BooleanField(blank=True)),
                ('ell', models.BooleanField(blank=True)),
                ('iep', models.BooleanField(blank=True)),
                ('a504', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackername', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(null=True)),
                ('ontask', models.BooleanField(blank=True)),
                ('followexpectation', models.BooleanField(blank=True)),
                ('askforhelp', models.BooleanField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='trackerapp.student')),
            ],
        ),
    ]
