# Generated by Django 4.1.4 on 2023-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_alter_tracker_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
